name: first_workflow
#on: workflow_dispatch
on: 
  push:
      branches: [ "main" ]
  pull_request:
      branches: [ "main" ]
jobs:
  setup:
    runs-on: ubuntu-slim
    steps:
      - name: clone-repo
        run: | 
          echo "hello clone repos step"
          echo "good afterroon running on single step of both echo commands"
          echo "----checking the present working directory----"
          pwd

  second-job:
    runs-on: ubuntu-slim
    steps:
      - name: second-stage
        run: echo "hello second-stage"
