name: first_workflow
#on: workflow_dispatch
on: 
  push:
      branches: [ "main" ]
  pull_request:
      branches: [ "main" ]
jobs:
  setup:
    runs-on: ubuntu-slim
    steps:
      - name: clone-repo
        uses: actions/checkout@v4

      - name: basic-step
        run: | 
          #!/bin/bash
          echo "hello clone repos step"
          echo "good afterroon running on single step of both echo commands"
          echo "----checking the present working directory----"
          pwd
          echo "---listing files----"
          ls -larth

      - name: listing-packages
        run: | 
          echo "---checking the java and python versions----"
          python --version
          chmod +x version.sh
          ./version.sh
          
  second-job:
    needs: setup
    runs-on: ubuntu-slim
    steps:
      - name: second-stage
        run: echo "hello second-stage"
